import { open_sans } from '@/globalStyles/fonts';
import 'normalize.css/normalize.css';
import "../globalStyles/main.scss";
import PageLayout from '@/components/layouts/PageLayout';



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={`${open_sans.className}`}>
        <PageLayout>
            {children}
        </PageLayout>
      </body>
    </html>
  );
}
