import { open_sans } from '@/globalStyles/fonts';
import 'normalize.css/normalize.css';
import "../globalStyles/main.scss";
import PageLayout from '@/components/layouts/PageLayout';
import { ToastContainer } from 'react-toastify';
import "react-toastify/dist/ReactToastify.css";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={`${open_sans.className}`}>
        <PageLayout>
        <ToastContainer
position="top-right"
autoClose={5000}
hideProgressBar={true}
newestOnTop={false}
closeOnClick={false}
rtl={false}
pauseOnFocusLoss
draggable
theme="light"
className="toast_container"
/>
            {children}
        </PageLayout>
      </body>
    </html>
  );
}
